name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Adjust the Node.js versions as needed

        steps:
          - name: step 1
            uses: actions/checkout@v1

          - name: Set up Node.js
            uses: actions/setup-node@v1
            # with:
            # node-version: ${{ matrix.node-version }}

          - name: Install Dependencies
            run: npm install

          - name: Build
            run: npm run build
