name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

        steps:
          - name: step 1
          - uses: actions/checkout@v1
          # - uses: actions/setup-node@v1
          # with:
          #   node-version: [20.x]
          - run: npm install
          - run: npm run build
